CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASS}';
CREATE USER IF NOT EXISTS '${WP_AMDIN_USER}'@'%' IDENTIFIED BY '${WP_ADMIN_PASS}';
GRANT ALL PRIVILEGES ON wordpress.* TO '${WP_ADMIN_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON wodpress.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;
