CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASS}';
CREATE USER IF NOT EXISTS '${WP_ADMIN_USER}'@'%' IDENTIFIED BY '${WP_ADMIN_PASS}';
GRANT ALL PRIVILEGES ON wordpress.* TO '${WP_ADMIN_USER}'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON wordpress.* TO '${DB_USER}'@'%' WITH GRANT OPTION;
--GRANT SELECT, INSERT, UPDATE, DELETE ON wordpress.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;
