global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']
  - job_name: 'wordpress_app'
    metrics_path: /wp-metrics.php
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['nginx:443']
  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: ['mysqld_exporter:9104']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
